import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {getValidLanguage} from "@/src/helpers";
import {cookies} from "next/headers";
import {LanguageProvider, ThemeProvider} from "@/src/context";
import {SiteShell} from "@/src/components/layout";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {

    const cookieStore = await cookies();
    const initialLang = getValidLanguage(cookieStore.get("lang")?.value);

    return (
        <html
            lang={initialLang}
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
        <body className="min-h-full flex flex-col">
        <ThemeProvider>
            <LanguageProvider initialLang={initialLang}>
                <SiteShell>{children}</SiteShell>
            </LanguageProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
